version: "3.7"

services:
    app:
        image: ${APP_NAME}-app-dev:local
        build:
            args:
                COMPOSER_AUTH: "${COMPOSER_AUTH}"
                DD_SERVICE:
                APP_VERSION:
                BUILD_START_TIME:
                LAST_COMMIT_DATE:
            context: .
            dockerfile: ./docker/Dockerfile
            target: app_dev
        environment:
            APP_ENV: dev
            OPCACHE_VALIDATE_TIMESTAMPS: 1
            DD_AGENT_HOST: datadog
            DD_TRACE_SYMFONY_ANALYTICS_ENABLED: "true"
        depends_on:
            - db
            - redis
        env_file:
            - ${ENV_FILE:-.env}
        volumes:
            - ./app:/var/www/html:rw,cached
    web:
        image: ${APP_NAME}-web:local
        build:
            args:
                ASSETS_IMAGE: "${APP_NAME}-app-dev:local"
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - ${APP_PORT}:80
        depends_on:
            - app
        volumes:
            - ./app/public:/var/www/html/public:ro,delegated
    cache:
        image: ${APP_NAME}-cache:local
        build:
            context: .
            dockerfile: ./docker/varnish/Dockerfile
        ports:
            - ${APP_CACHE_PORT}:80
        depends_on:
            - web
        links:
            - web
    db:
        image: mongo:4.4
        environment:
            MONGO_INITDB_DATABASE: api
            MONGO_INITDB_ROOT_USERNAME: api
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - db_data:/var/lib/mongodb/data:rw
    redis:
        image: redis:5.0-alpine
        volumes:
            - redis_data:/data/redis:rw
volumes:
    db_data: {}
    redis_data: {}
