version: "3.7"

services:
    app:
        image: ${APP_NAME}-app-prod:local
        build:
            args:
                COMPOSER_AUTH: "${COMPOSER_AUTH}"
                APP_VERSION:
                BUILD_START_TIME:
                LAST_COMMIT_DATE:
            context: .
            dockerfile: ./docker/Dockerfile
            target: app
        env_file:
            - ${ENV_FILE:-.env}
    web:
        image: ${APP_NAME}-web:local
        build:
            args:
                ASSETS_IMAGE: "${APP_NAME}-app-prod:local"
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - ${APP_PORT}:80
        depends_on:
            - app
    cache:
        image: ${APP_NAME}-cache:local
        build:
            context: .
            dockerfile: ./docker/varnish/Dockerfile
        ports:
            - ${APP_CACHE_PORT}:80
        depends_on:
            - web
